default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: global-registry-interface_development

test:
  <<: *default
  database: global-registry-interface_test

production:
  <<: *default
  database: global-registry-interface_production
  username: global-registry-interface
  password: <%= ENV['GLOBAL-REGISTRY-INTERFACE_DATABASE_PASSWORD'] %>
